name: fennec_jwt
description: dart plugin for generate and validate jwt
version: 0.0.2
homepage: https://github.com/Fennec-Framework/fennec_jwt

environment:
  sdk: ">=2.16.2 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
dependencies:
  crypto: ^3.0.2
