name: fennec_jwt
description: A simple command-line application.
version: 0.0.1
homepage: https://github.com/Fennec-Framework/fennec_jwt

environment:
  sdk: ">=2.16.2 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
dependencies:
  crypto: ^3.0.2
